mj:
  discord:
    guild-id: 1119105874905014333
    channel-id: 1119105875714523208
    user-token: MTEwNTk0NTE1NzQ1MjQ0MzgzOA.GLkfzM.sqzYYerIr0wp8NC-w6iNOaS8SHRReWgL0m4qeI
    user-wss: true
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
    id-prefix: "["
    id-suffix: "]"
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  queue:
    timeout-minutes: 5
    core-size: 3
    queue-size: 10